# Generated by Django 6.0 on 2025-12-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('motivation', models.TextField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='Qemal Stafa', max_length=200),
        ),
    ]
